In [1]:
import pandas as pd

In [2]:
providers = pd.read_csv("providers_data.csv")
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577

In [3]:
providers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   Address      1000 non-null   object
 4   City         1000 non-null   object
 5   Contact      1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [4]:
providers.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='object')

In [5]:
providers['Provider_ID'].is_unique

True

In [6]:
receivers=pd.read_csv("receivers_data.csv")
receivers.head()

   Receiver_ID          Name        Type               City           Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     (955)922-5295
1            2  Laurie Ramos  Individual         Lewisburgh      761.042.1570
2            3  Ashley Mckee         NGO  South Randalltown  691-023-0094x856
3            4    Erika Rose         NGO   South Shaneville        8296491111
4            5   John Romero  Individual          Bakerport      067.491.0154

In [7]:
receivers['Receiver_ID'].is_unique

True

In [8]:
receivers.columns

Index(['Receiver_ID', 'Name', 'Type', 'City', 'Contact'], dtype='object')

In [9]:
receivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   City         1000 non-null   object
 4   Contact      1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [10]:
listings = pd.read_csv("food_listings_data.csv")
listings.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner

In [11]:
listings['Food_ID'].is_unique

True

In [12]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   object
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   object
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   object
 6   Location       1000 non-null   object
 7   Food_Type      1000 non-null   object
 8   Meal_Type      1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.4+ KB

In [13]:
listings.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='object')

In [14]:
claims = pd.read_csv("claims_data.csv")
claims.head()

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

In [15]:
claims['Claim_ID'].is_unique

True

In [16]:
claims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   object
 4   Timestamp    1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [17]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='object')

In [18]:
listings['Provider_ID'].isin(providers['Provider_ID']).all()

np.True_

In [19]:
import sqlite3

conn = sqlite3.connect("food_waste.db")

In [20]:
pd.read_sql("""
SELECT name 
FROM sqlite_master 
WHERE type='table';
""", conn)

             name
0  food_providers
1  food_receivers
2   food_listings
3          claims

In [21]:
providers.to_sql("food_providers", conn, if_exists="replace", index=False)
receivers.to_sql("food_receivers", conn, if_exists="replace", index=False)
listings.to_sql("food_listings", conn, if_exists="replace", index=False)
claims.to_sql("claims", conn, if_exists="replace", index=False)

1000

In [22]:
pd.read_sql("""
SELECT name 
FROM sqlite_master 
WHERE type='table';
""", conn)

             name
0  food_providers
1  food_receivers
2   food_listings
3          claims

In [23]:
#Q1 ---> How many food providers and receivers are there in each city?

pd.read_sql("""
SELECT City, COUNT(*) AS provider_count
FROM food_providers
GROUP BY City;
""", conn)

                 City  provider_count
0            Adambury               1
1           Adamsview               1
2          Adamsville               1
3        Aguirreville               1
4    Alexanderchester               1
..                ...             ...
958       Wrightville               1
959         Yatesside               1
960      Youngchester               1
961      Zimmermanton               1
962    Zimmermanville               1

[963 rows x 2 columns]

In [24]:
#Q1 ---> How many food providers and receivers are there in each city?

pd.read_sql("""
SELECT City, COUNT(*) AS receiver_count
FROM food_receivers
GROUP BY City;
""", conn)

              City  receiver_count
0       Aaronshire               1
1         Adamland               1
2      Aguilarbury               1
3      Aguilarstad               1
4    Alexanderbury               1
..             ...             ...
961    Woodardview               1
962      Woodsfurt               1
963     Wrightland               1
964       Wyattton               1
965    Zacharyview               1

[966 rows x 2 columns]

In [25]:
#Q2---> Which type of food provider (restaurant, grocery store, etc.) contributes the most food?

pd.read_sql("""
SELECT Provider_Type, SUM(Quantity)
FROM food_listings
GROUP BY Provider_Type;
""", conn)

      Provider_Type  SUM(Quantity)
0  Catering Service           6116
1     Grocery Store           6059
2        Restaurant           6923
3       Supermarket           6696

In [26]:
#Q3 ---> What is the contact information of food providers in a specific city?
pd.read_sql("""
SELECT Name, Contact
FROM food_providers
WHERE City = 'New Jessica';
""", conn)

               Name          Contact
0  Gonzales-Cochran  +1-600-220-0480

In [27]:
#Q4 ---> Which receivers have claimed the most food?

pd.read_sql("""
SELECT r.Name, COUNT(*) AS total_claims
FROM claims c
JOIN food_receivers r
ON c.Receiver_ID = r.Receiver_ID
GROUP BY r.Name;
""", conn)

                  Name  total_claims
0         Aaron Keller             1
1           Aaron Rios             2
2          Aaron Scott             1
3     Abigail Crawford             3
4        Adam Browning             1
..                 ...           ...
615     William Barnes             1
616        William Fox             1
617  William Frederick             5
618     Yvette Huffman             2
619      Zachary Lewis             1

[620 rows x 2 columns]

In [28]:
#Q5---> What is the total quantity of food available from all providers?

pd.read_sql("""
SELECT SUM(Quantity) AS total_food_available
FROM food_listings;
""", conn)

   total_food_available
0                 25794

In [29]:
#Q6---> Which city has the highest number of food listings?

pd.read_sql("""
SELECT Location, COUNT(*) AS total_listings
FROM food_listings
GROUP BY Location
ORDER BY total_listings DESC;
""", conn)

             Location  total_listings
0       South Kathryn               6
1           New Carol               6
2           Perezport               5
3           Jimmyberg               5
4         East Angela               5
..                ...             ...
619     Andersonmouth               1
620       Amandashire               1
621      Allenborough               1
622  Alexanderchester               1
623          Adambury               1

[624 rows x 2 columns]

In [30]:
#Q7---> What are the most commonly available food types?

pd.read_sql("""
SELECT Food_Type, COUNT(*) AS count
FROM food_listings
GROUP BY Food_Type
ORDER BY count DESC;
""", conn)

        Food_Type  count
0      Vegetarian    336
1           Vegan    334
2  Non-Vegetarian    330

In [31]:
# Q8 ---> Number of claims per food item
pd.read_sql("""
SELECT f.Food_Name, COUNT(c.Claim_ID) AS total_claims
FROM claims c
JOIN food_listings f
ON c.Food_ID = f.Food_ID
GROUP BY f.Food_Name;
""", conn)

    Food_Name  total_claims
0       Bread            94
1     Chicken           102
2       Dairy           110
3        Fish           108
4      Fruits            71
5       Pasta            87
6        Rice           122
7       Salad           106
8        Soup           114
9  Vegetables            86

In [32]:
#Q9 Which provider has had the highest number of successful food claims?
pd.read_sql("""
SELECT food_providers.Name, COUNT(*) AS claims_count
FROM claims
JOIN food_listings
ON claims.Food_ID = food_listings.Food_ID
JOIN food_providers
ON food_listings.Provider_ID = food_providers.Provider_ID
GROUP BY food_providers.Name
ORDER BY claims_count DESC
LIMIT 1;
""", conn)

                Name  claims_count
0  Butler-Richardson            12

In [33]:
#Q10. What percentage of food claims are completed vs. pending vs. canceled?

pd.read_sql("""
SELECT Status,
       COUNT(*) * 100.0 / (SELECT COUNT(*) FROM claims) AS percentage
FROM claims
GROUP BY Status;
""", conn)

      Status  percentage
0  Cancelled        33.6
1  Completed        33.9
2    Pending        32.5

In [34]:
#Q11. What is the average quantity of food claimed per receiver?
pd.read_sql("""
SELECT r.Name, AVG(f.Quantity) AS avg_quantity_claimed
FROM claims c
JOIN food_listings f
ON c.Food_ID = f.Food_ID
JOIN food_receivers r
ON c.Receiver_ID = r.Receiver_ID
GROUP BY r.Name;
""", conn)

                  Name  avg_quantity_claimed
0         Aaron Keller             39.000000
1           Aaron Rios             21.000000
2          Aaron Scott             45.000000
3     Abigail Crawford             25.666667
4        Adam Browning              5.000000
..                 ...                   ...
615     William Barnes             47.000000
616        William Fox             12.000000
617  William Frederick             21.400000
618     Yvette Huffman             45.000000
619      Zachary Lewis             22.000000

[620 rows x 2 columns]

In [35]:
#Q12. Which meal type (breakfast, lunch, dinner, snacks) is claimed the most?
pd.read_sql("""
SELECT f.Meal_Type, COUNT(*) AS claims_count
FROM claims c
JOIN food_listings f
ON c.Food_ID = f.Food_ID
GROUP BY f.Meal_Type
ORDER BY claims_count DESC;
""", conn)

   Meal_Type  claims_count
0  Breakfast           278
1      Lunch           250
2     Snacks           240
3     Dinner           232

In [36]:
#Q13 What is the total quantity of food donated by each provider?
pd.read_sql("""
SELECT p.Name, SUM(f.Quantity) AS total_food_donated
FROM food_listings f
JOIN food_providers p
ON f.Provider_ID = p.Provider_ID
GROUP BY p.Name;
""", conn)

                             Name  total_food_donated
0       Abbott, Brooks and Moreno                  47
1                 Abbott-Robinson                  44
2                     Adams-Meyer                  28
3                     Adams-Young                  16
4                   Aguilar Group                  66
..                            ...                 ...
623  Young, Townsend and Mccarthy                  87
624                    Young-Luna                  35
625                      Young-Wu                   2
626                  Yu-Rodriguez                  14
627                     Zhang LLC                  76

[628 rows x 2 columns]

In [37]:
#Q14 Which type of receiver (NGO, Community Center, Individual) prefers which food types?
pd.read_sql("""
SELECT r.Type AS receiver_type, f.Food_Type, COUNT(*) AS claims_count
FROM claims c
JOIN food_listings f
ON c.Food_ID = f.Food_ID
JOIN food_receivers r
ON c.Receiver_ID = r.Receiver_ID
GROUP BY r.Type, f.Food_Type
ORDER BY claims_count DESC;
""", conn)

   receiver_type       Food_Type  claims_count
0            NGO      Vegetarian           108
1        Charity  Non-Vegetarian            91
2        Charity      Vegetarian            90
3        Charity           Vegan            87
4     Individual  Non-Vegetarian            85
5            NGO  Non-Vegetarian            84
6        Shelter           Vegan            81
7            NGO           Vegan            80
8        Shelter      Vegetarian            78
9     Individual      Vegetarian            74
10    Individual           Vegan            71
11       Shelter  Non-Vegetarian            71

In [38]:
#Q15 What is the total quantity of food donated by each provider
pd.read_sql("""
SELECT p.Name, AVG(f.Quantity) AS avg_food_provided
FROM food_listings f
JOIN food_providers p
ON f.Provider_ID = p.Provider_ID
GROUP BY p.Name;
""", conn)

                             Name  avg_food_provided
0       Abbott, Brooks and Moreno          47.000000
1                 Abbott-Robinson          44.000000
2                     Adams-Meyer          28.000000
3                     Adams-Young          16.000000
4                   Aguilar Group          33.000000
..                            ...                ...
623  Young, Townsend and Mccarthy          29.000000
624                    Young-Luna          35.000000
625                      Young-Wu           2.000000
626                  Yu-Rodriguez          14.000000
627                     Zhang LLC          25.333333

[628 rows x 2 columns]